import type { Metadata } from "next";
import { Geist, Geist_Mono,Outfit  } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "PortSoftware",
  // icons: {
  //   icon: "/favicon.ico", 
  // },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.variable}>
       <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
